# Generated by Django 5.0.3 on 2024-05-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elementt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('left', models.IntegerField()),
                ('top', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Element',
        ),
    ]
