# Generated by Django 5.0.3 on 2024-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_elementt_delete_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Elementt',
        ),
    ]
