# Generated by Django 5.0.3 on 2024-05-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_savep_delete_elementt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save_P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('coordinates', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='SaveP',
        ),
    ]
