# Generated by Django 5.0.3 on 2024-05-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_save_p_delete_savep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save_Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('coordinates', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='imager/')),
            ],
        ),
    ]
