# Generated by Django 5.0.3 on 2024-05-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_myimagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('coordinates', models.CharField(blank=True, max_length=50, null=True)),
                ('src', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
