# Generated by Django 5.0.3 on 2024-05-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveFilesModell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('filee', models.FileField(upload_to='files/')),
                ('time', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='SaveFilesModel',
        ),
    ]
